import {describe, expect, it} from 'vitest';
import {flightTotal, stayTotal, rentalTotal, rentalCycles, sameRental, priceDifference, validCents, flightComparable, stayComparable} from './planSearchComparison';
import {flight, stay, rental, flightOption, stayOption} from './planSearchFixtures';
import type {FlightCombinationResponse, StayOptionResponse} from '../api/tripsApi';
describe('full component price evidence', () => {
  it('includes both legs and all fees for the saved party', () => {expect(flightTotal(flight, 3)).toBe(1110); expect(flightTotal({...flight, outboundTaxCents: undefined as never}, 3)).toBeUndefined(); expect(flightTotal(flight, 0)).toBeUndefined();});
  it('includes every night and required room', () => {expect(stayTotal(stay)).toBe(1040); expect(stayTotal({...stay, nights: []})).toBeUndefined(); expect(stayTotal({...stay, unitCount: 0})).toBeUndefined();});
  it('uses consecutive 24 hour rental cycles and normalized interval identity', () => {expect(rentalTotal(rental)).toBe(130); expect(rentalTotal({...rental, returnAt: '2027-03-11T10:01:00Z'})).toBe(260); expect(sameRental(rental, 1, '2027-03-10T03:00:00-07:00', rental.returnAt)).toBe(true); expect(sameRental(rental, 1, rental.pickupAt, '2027-03-12T10:00:00Z')).toBe(false); expect(rentalCycles('invalid', rental.returnAt)).toBeUndefined(); expect(rentalTotal({...rental, returnAt: rental.pickupAt})).toBeUndefined();});
  it.each([undefined, null, NaN, Infinity, -1, 0.5])('rejects unavailable/invalid evidence %s', value => {expect(validCents(value)).toBe(false); expect(priceDifference(value, 100)).toBe('Comparison unavailable'); expect(priceDifference(100, value)).toBe('Comparison unavailable');});
  it('retains valid zero and signed full total differences', () => {expect(priceDifference(0, 0)).toBe('Same price as current selection'); expect(priceDifference(200, 100)).toBe('$1.00 less than current selection'); expect(priceDifference(100, 200)).toBe('$1.00 more than current selection');});
  it('requires dates and party evidence for flight comparison', () => {const option = flightOption; expect(flightComparable(flight, option, '2027-03-10', '2027-03-14', 3)).toBe(true); expect(flightComparable({...flight, outboundDepartureTime: undefined}, option, '2027-03-10', '2027-03-14', 3)).toBe(false); expect(flightComparable(flight, option, '2027-03-10', '2027-03-14', 2)).toBe(false); expect(flightComparable(flight, {...option, outbound: {...option.outbound, departureTime: '2027-03-11T12:00:00Z'}}, '2027-03-10', '2027-03-14', 3)).toBe(false);});
  it('requires full saved and prospective stay dates and matching rooms', () => {const option = stayOption; expect(stayComparable(stay, option, '2027-03-10', '2027-03-14')).toBe(true); expect(stayComparable({...stay, unitCount: 1}, option, '2027-03-10', '2027-03-14')).toBe(false); expect(stayComparable({...stay, nights: stay.nights.slice(1)}, option, '2027-03-10', '2027-03-14')).toBe(false); expect(stayComparable(stay, {...option, pricing: {...option.pricing, nights: []}}, '2027-03-10', '2027-03-14')).toBe(false);});
});

