import {act, fireEvent, render, screen, within, waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest';
import {TripComparisonPage} from './TripComparisonPage';
import {tripsApi, type TripResponse, type FlightCombinationResponse, type StayOptionResponse, type RentalOptionResponse} from '../api/tripsApi';
import {flight, stay, rental, flightOption, stayOption, rentalOption} from './planSearchFixtures';
const trip = {id: 'trip', version: 3, destinationKey: 'destination-sfo', destinationName: 'San Francisco', originAirportCode: 'PDX', startDate: '2027-03-10', endDate: '2027-03-14', travelerCount: 3, travelerAges: [25,30,10]} as TripResponse;
const tally = {airfareTotalCents: 1110, stayTotalCents: 1040, rentalTotalCents: 130, grandTotalCents: 9876, partial: true, remainingBudgetCents: null, budgetOverageCents: null, isOverBudget: false};
function props() {return {trip, draftId: 'selected', name: 'My plan', initialSearch: null, tally, savedAirfare: flight, savedStay: stay, savedRental: rental, onSelectAirfare: vi.fn().mockResolvedValue(true), onSelectStay: vi.fn().mockResolvedValue(true), onSelectRental: vi.fn().mockResolvedValue(true), onRemoveAirfare: vi.fn(), onRemoveStay: vi.fn(), onRemoveRental: vi.fn()};}
beforeEach(() => {vi.spyOn(tripsApi, 'searchAirfare').mockResolvedValue({options: [flightOption]} as never); vi.spyOn(tripsApi, 'searchStays').mockResolvedValue({options: [stayOption]} as never); vi.spyOn(tripsApi, 'searchRentals').mockResolvedValue({options: [rentalOption], driverEligible: true, selectionDisabled: false} as never); vi.spyOn(tripsApi, 'searchPublicAirfare').mockResolvedValue({options: [flightOption]} as never); vi.spyOn(tripsApi, 'searchPublicStays').mockResolvedValue({options: [stayOption]} as never);});
afterEach(() => vi.restoreAllMocks());
describe('search-first planning', () => {
  it.each([0, 1, 2, 3])('keeps guest selection mask %s local with no rental search', async mask => {
    render(<TripComparisonPage {...props()} guest guestAirfare={mask & 1 ? flightOption : undefined} guestStay={mask & 2 ? stayOption : undefined} />);
    const summary = screen.getByRole('region', {name: 'Your selections'}); expect(within(summary).getAllByRole('article')).toHaveLength(2); expect(summary).toHaveTextContent('Not yet saved'); expect(screen.queryByRole('tab', {name: 'Search cars'})).not.toBeInTheDocument(); expect(tripsApi.searchRentals).not.toHaveBeenCalled(); await waitFor(() => expect(tripsApi.searchPublicAirfare).toHaveBeenCalled());
  });
  it.each([undefined, [24], [25]])('preserves rental driver boundary %s', async ages => {
    render(<TripComparisonPage {...props()} trip={{...trip, travelerAges: ages ?? null}} initialSearch="RENTAL" savedRental={null} />);
    const button = await screen.findByRole('button', {name: 'Save car to plan'}); if (ages?.[0] === 25) expect(button).toBeEnabled(); else expect(button).toBeDisabled();
  });
  it('preserves server rental restrictions and rejects invalid intervals without searching or selecting', async () => {
    vi.mocked(tripsApi.searchRentals).mockResolvedValue({options: [rentalOption], driverEligible: true, selectionDisabled: true, disabledReason: 'Inventory cannot be selected'} as never);
    render(<TripComparisonPage {...props()} initialSearch="RENTAL" />); expect(await screen.findByRole('button', {name: 'Replace car'})).toBeDisabled(); expect(screen.getByRole('alert')).toHaveTextContent('Inventory cannot be selected');
    const calls = vi.mocked(tripsApi.searchRentals).mock.calls.length; fireEvent.change(screen.getByLabelText('Return date & time'), {target: {value: '2027-03-09T10:00'}}); expect(await screen.findByText(/Return date and time must be after/)).toBeInTheDocument(); expect(tripsApi.searchRentals).toHaveBeenCalledTimes(calls); expect(screen.queryByRole('button', {name: 'Replace car'})).not.toBeInTheDocument();
  });
  it('identifies the same car and interval, but confirms the same car over a changed interval', async () => {
    const p = props(); p.savedRental = {...rental, pickupAt: '2027-03-10T10:00:00-08:00', returnAt: '2027-03-14T10:00:00-07:00'};
    vi.mocked(tripsApi.searchRentals).mockResolvedValue({options: [{...rentalOption, rentalUnitId: 1}], driverEligible: true} as never);
    render(<TripComparisonPage {...p} initialSearch="RENTAL" />); expect(await screen.findByRole('button', {name: 'Selected'})).toBeDisabled(); fireEvent.change(screen.getByLabelText('Return date & time'), {target: {value: '2027-03-13T10:00'}});
    const user = userEvent.setup(); await user.click(await screen.findByRole('button', {name: 'Replace car'})); expect(screen.getByRole('dialog')).toHaveTextContent('2027-03-14T10:00:00-07:00'); expect(screen.getByRole('dialog')).toHaveTextContent('2027-03-13T10:00:00-08:00'); expect(p.onSelectRental).not.toHaveBeenCalled();
  });
  it.each(['stay', 'car'] as const)('retains %s failure, retry and empty states', async category => {
    const api = category === 'stay' ? tripsApi.searchStays : tripsApi.searchRentals; vi.mocked(api).mockRejectedValueOnce(new Error('Offline')).mockResolvedValueOnce({options: []} as never);
    render(<TripComparisonPage {...props()} initialSearch={category === 'stay' ? 'STAY' : 'RENTAL'} />); const user = userEvent.setup(); await user.click(await screen.findByRole('button', {name: category === 'stay' ? 'Retry stay search' : 'Retry rental search'})); expect(await screen.findByText(category === 'stay' ? /No accommodations found/ : /No rental cars found/)).toBeInTheDocument();
  });
  it.each(Array.from({length: 8}, (_, i) => i))('uses one summary/layout for saved selection mask %s', async mask => {
    const p = {...props(), savedAirfare: mask & 1 ? flight : null, savedStay: mask & 2 ? stay : null, savedRental: mask & 4 ? rental : null}; render(<TripComparisonPage {...p} />);
    expect(screen.getAllByRole('heading', {name: 'Build your plan'})).toHaveLength(1); const summary = screen.getByRole('region', {name: 'Your selections'}); expect(summary).toHaveTextContent('Partial total: $98.76'); expect(within(summary).getAllByRole('article')).toHaveLength(3); expect(within(summary).queryAllByText('Not selected')).toHaveLength(3 - Number(Boolean(mask & 1)) - Number(Boolean(mask & 2)) - Number(Boolean(mask & 4))); expect(screen.queryByText('Compare more options')).not.toBeInTheDocument(); await screen.findByRole('button', {name: mask & 1 ? 'Replace flight' : 'Save flight to plan'});
  });
  it('distinguishes unknown and valid zero totals and honors server partial', async () => {const p = props(); const r = render(<TripComparisonPage {...p} tally={undefined} />); expect(screen.getByRole('region', {name: 'Your selections'})).toHaveTextContent('Total unavailable'); r.rerender(<TripComparisonPage {...p} tally={{...tally, grandTotalCents: 0, partial: false}} />); expect(screen.getByRole('region', {name: 'Your selections'})).toHaveTextContent('Total: $0.00'); await screen.findByRole('button', {name: 'Replace flight'});});
  it.each([{initialSearch: 'STAY', lockedAirfare: false, lockedStay: false, lockedRental: false, expected: 'Search stays'}, {initialSearch: null, lockedAirfare: true, lockedStay: false, lockedRental: false, expected: 'Search stays'}, {initialSearch: null, lockedAirfare: true, lockedStay: true, lockedRental: false, expected: 'Search cars'}] as const)('chooses usable hinted/fallback $expected', async flags => {render(<TripComparisonPage {...props()} {...flags} />); expect(screen.getByRole('tab', {name: flags.expected})).toHaveAttribute('aria-selected', 'true'); await waitFor(() => expect(flags.expected === 'Search cars' ? tripsApi.searchRentals : tripsApi.searchStays).toHaveBeenCalled());});
  it.each([true, false])('opens no unusable search when all locked or canceled (%s)', readOnly => {render(<TripComparisonPage {...props()} readOnly={readOnly} lockedAirfare lockedStay lockedRental />); expect(screen.getByText(/This plan is read-only/)).toBeInTheDocument(); expect(tripsApi.searchAirfare).not.toHaveBeenCalled(); expect(tripsApi.searchRentals).not.toHaveBeenCalled(); expect(screen.getByRole('button', {name: 'Remove flight'})).toBeDisabled();});
  it('opens the first available search when resolved purchase history releases a category', async () => {const p = props(), mounted = render(<TripComparisonPage {...p} lockedAirfare lockedStay lockedRental />); mounted.rerender(<TripComparisonPage {...p} lockedAirfare lockedRental />); expect(screen.getByRole('tab', {name: 'Search stays'})).toHaveAttribute('aria-selected', 'true'); await screen.findByRole('button', {name: 'Replace stay'});});
  it('keeps an enabled tab reachable when the manually focused category becomes locked', async () => {
    const p = props(), mounted = render(<TripComparisonPage {...p} initialSearch="STAY" />);
    const user = userEvent.setup(), stays = screen.getByRole('tab', {name: 'Search stays'});
    stays.focus(); await user.keyboard('{ArrowLeft}');
    expect(screen.getByRole('tab', {name: 'Search flights'})).toHaveFocus();
    mounted.rerender(<TripComparisonPage {...p} initialSearch="STAY" lockedAirfare />);
    expect(stays).toHaveAttribute('aria-selected', 'true');
    expect(stays).toHaveAttribute('tabindex', '0');
    expect(within(screen.getByRole('tablist')).getAllByRole('tab').filter(tab => !tab.hasAttribute('disabled') && tab.tabIndex === 0)).toHaveLength(1);
    await screen.findByRole('button', {name: 'Replace stay'});
  });
  it('uses manual activation, enabled roving focus and linked unique panels', async () => {render(<TripComparisonPage {...props()} lockedStay />); const user = userEvent.setup(), flights = screen.getByRole('tab', {name: 'Search flights'}), cars = screen.getByRole('tab', {name: 'Search cars'}); flights.focus(); await user.keyboard('{ArrowRight}'); expect(cars).toHaveFocus(); expect(flights).toHaveAttribute('aria-selected', 'true'); await user.keyboard('{Enter}'); expect(cars).toHaveAttribute('aria-selected', 'true'); expect(screen.getByRole('tabpanel', {name: 'Search cars'})).toHaveAttribute('id', cars.getAttribute('aria-controls')); await user.keyboard('{Home}'); expect(flights).toHaveFocus(); await user.keyboard('{End}'); expect(cars).toHaveFocus(); expect(within(screen.getByRole('tablist')).getAllByRole('tab').filter(t => t.tabIndex === 0)).toHaveLength(1); await screen.findByRole('button', {name: 'Replace car'});});
  it('change actions focus matching search without a save', async () => {const p = props(); render(<TripComparisonPage {...p} />); const user = userEvent.setup(); await user.click(screen.getByRole('button', {name: 'Change stay'})); expect(screen.getByRole('tab', {name: 'Search stays'})).toHaveFocus(); expect(p.onSelectStay).not.toHaveBeenCalled(); expect(screen.getByRole('region', {name: 'Current selection'})).toHaveTextContent('Old hotel'); await screen.findByRole('button', {name: 'Replace stay'});});
  it.each(['flight', 'stay', 'car'] as const)('confirms %s, cancel/failure keeps old choice and retry updates only after success', async category => {
    const p = props(), save = category === 'flight' ? p.onSelectAirfare : category === 'stay' ? p.onSelectStay : p.onSelectRental;
    save.mockResolvedValueOnce(false).mockResolvedValueOnce(true); render(<TripComparisonPage {...p} />); const user = userEvent.setup(); await user.click(screen.getByRole('tab', {name: 'Search ' + (category === 'flight' ? 'flights' : category === 'stay' ? 'stays' : 'cars')}));
    await user.click(await screen.findByRole('button', {name: 'Replace ' + category})); let dialog = screen.getByRole('dialog'); expect(dialog).toHaveTextContent('Current choice'); expect(dialog).toHaveTextContent('New choice'); expect(dialog).toHaveTextContent('taxes and fees included'); expect(save).not.toHaveBeenCalled(); await user.click(within(dialog).getByRole('button', {name: 'Cancel'})); expect(save).not.toHaveBeenCalled();
    const trigger = await screen.findByRole('button', {name: 'Replace ' + category}); await user.click(trigger); dialog = screen.getByRole('dialog'); expect(within(dialog).getByRole('button', {name: 'Confirm replacement'})).toHaveFocus(); await user.click(within(dialog).getByRole('button', {name: 'Confirm replacement'})); expect(await within(dialog).findByRole('alert')).toHaveTextContent('previous selection is unchanged'); expect(screen.getByRole('region', {name: 'Your selections'})).toHaveTextContent('$98.76'); await user.click(within(dialog).getByRole('button', {name: 'Confirm replacement'})); await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument()); expect(save).toHaveBeenCalledTimes(2);
  });
  it('blocks duplicate submit/dismissal and traps focus while pending', async () => {const p = props(); let done!: (ok: boolean) => void; p.onSelectAirfare.mockImplementation(() => new Promise(resolve => {done = resolve;})); render(<TripComparisonPage {...p} />); const user = userEvent.setup(); await user.click(await screen.findByRole('button', {name: 'Replace flight'})); const dialog = screen.getByRole('dialog'); const confirm = within(dialog).getByRole('button', {name: 'Confirm replacement'}), cancel = within(dialog).getByRole('button', {name: 'Cancel'}); cancel.focus(); await user.tab(); expect(confirm).toHaveFocus(); await user.click(confirm); await user.click(confirm); await user.keyboard('{Escape}'); expect(dialog).toBeInTheDocument(); expect(cancel).toBeDisabled(); expect(p.onSelectAirfare).toHaveBeenCalledTimes(1); await act(async () => done(true)); expect(screen.queryByRole('dialog')).not.toBeInTheDocument();});
  it('invalidates candidates when saved context or permissions change', async () => {const p = props(), mounted = render(<TripComparisonPage {...p} />), user = userEvent.setup(); await user.click(await screen.findByRole('button', {name: 'Replace flight'})); mounted.rerender(<TripComparisonPage {...p} lockedAirfare />); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); expect(p.onSelectAirfare).not.toHaveBeenCalled();});
  it('marks exact flight and stay identities selected, and uses full total differences', async () => {const p = props(); const same = {...flightOption, pricing: {...flightOption.pricing, partyTotalPriceCents: 1110}, combinationKey: 'same', outbound: {...flightOption.outbound, flightInstanceId: 1}, returnFlight: {...flightOption.returnFlight, flightInstanceId: 2}}; vi.mocked(tripsApi.searchAirfare).mockResolvedValue({options: [same, flightOption]} as never); render(<TripComparisonPage {...p} />); expect(await screen.findByRole('button', {name: 'Selected'})).toBeDisabled(); expect(screen.getAllByText('$3.90 more than current selection')).toHaveLength(1); const user = userEvent.setup(); await user.click(screen.getByRole('tab', {name: 'Search stays'})); expect(await screen.findByText('$1.60 more than current selection')).toBeInTheDocument();});
  it('adds missing components directly and keeps guest choices local without car capability', async () => {const p = {...props(), guest: true, savedAirfare: null, savedStay: null}; render(<TripComparisonPage {...p} />); const user = userEvent.setup(); expect(screen.queryByRole('tab', {name: 'Search cars'})).not.toBeInTheDocument(); await user.click(await screen.findByRole('button', {name: 'Add flight'})); expect(p.onSelectAirfare).toHaveBeenCalledOnce(); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); expect(tripsApi.searchRentals).not.toHaveBeenCalled(); expect(screen.getByRole('region', {name: 'Your selections'})).toHaveTextContent('Not yet saved');});
  it('retains loading, retry, empty and stale suppression', async () => {let done!: (value: never) => void; vi.mocked(tripsApi.searchAirfare).mockImplementationOnce(() => new Promise(resolve => {done = resolve;})); render(<TripComparisonPage {...props()} />); expect(screen.getByText('Searching flights…')).toBeInTheDocument(); const user = userEvent.setup(); await user.click(screen.getByRole('tab', {name: 'Search stays'})); await act(async () => done({options: [flightOption]} as never)); expect(screen.queryByText('New Air')).not.toBeInTheDocument(); vi.mocked(tripsApi.searchAirfare).mockRejectedValueOnce(new Error('Offline')).mockResolvedValueOnce({options: []} as never); await user.click(screen.getByRole('tab', {name: 'Search flights'})); await user.click(await screen.findByRole('button', {name: 'Retry flight search'})); expect(await screen.findByText(/No flights found/)).toBeInTheDocument();});
});
