"""Enumerate the proposed fixture universe; no model, network, or app required.

This is a design calculator, not production booking validation. Run from any
directory with Python 3.10+: python scripts/verify-design.py
"""
import json
from datetime import datetime, timedelta
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / "design/weekend-inventory.json").read_text(encoding="utf-8"))
request = data["request"]
dt = datetime.fromisoformat


def minutes(value):
    return timedelta(minutes=value)


def calculate(outbound, inbound, hotel):
    out_mode, in_mode = (data["modes"][leg["mode"]] for leg in (outbound, inbound))
    out_transfer, in_transfer = (hotel["transfers"][leg["mode"]] for leg in (outbound, inbound))
    transport = request["partySize"] * (outbound["farePerPersonCents"] + inbound["farePerPersonCents"])
    lodging = request["nights"] * request["rooms"] * hotel["nightlyRoomCents"]
    transfers = sum((out_transfer["partyCents"], in_transfer["partyCents"],
                     out_mode["bostonTransferPartyCents"], in_mode["bostonTransferPartyCents"]))
    hotel_arrival = dt(outbound["arrives"]) + minutes(out_mode["arrivalBufferMinutes"] + out_transfer["minutes"])
    check_in = dt(f'{request["outboundDate"]}T{hotel["checkIn"]}:00-04:00')
    ready = max(hotel_arrival, check_in)
    hotel_departure = dt(inbound["departs"]) - minutes(in_mode["departureBufferMinutes"] + in_transfer["minutes"])
    home = dt(inbound["arrives"]) + minutes(in_mode["arrivalBufferMinutes"] + in_mode["bostonTransferMinutes"])
    start = dt(outbound["departs"]) - minutes(out_mode["departureBufferMinutes"] + out_mode["bostonTransferMinutes"])
    reasons = []
    if ready > dt(request["hotelReadyBy"]):
        reasons.append("late hotel arrival")
    if hotel_departure < dt(request["leaveHotelNoEarlierThan"]):
        reasons.append("leaves hotel too early")
    if home > dt(request["homeBy"]):
        reasons.append("late Boston return")
    if transport + lodging + transfers > request["budgetCents"]:
        reasons.append("over budget")
    if min(outbound["seats"], inbound["seats"]) < request["partySize"] or hotel["roomsPerNight"] < request["rooms"]:
        reasons.append("insufficient inventory")
    if hotel["roomCapacity"] * request["rooms"] < request["partySize"]:
        reasons.append("room capacity")
    return dict(id=f'{outbound["id"]}/{inbound["id"]}/{hotel["id"]}', transport=transport,
                lodging=lodging, transfers=transfers, total=transport + lodging + transfers,
                ready=ready, start=start, leave=hotel_departure, home=home, reasons=reasons)


rows = [calculate(*items) for items in product(
    [s for s in data["services"] if s["direction"] == "outbound"],
    [s for s in data["services"] if s["direction"] == "return"], data["hotels"])]
by_id = {row["id"]: row for row in rows}

# Independent hand-calculated anchors protect the intended demo story.
expected = {
    "RAIL-OUT/RAIL-RETURN/CENTRAL": (84000, "15:00"),
    "RAIL-OUT/RAIL-RETURN/GARDEN": (98000, "15:00"),
    "RAIL-OUT/RAIL-RETURN/RIVERSIDE": (86000, "15:15"),
    "AIR-OUT/AIR-RETURN/CENTRAL": (96000, "15:55"),
    "AIR-LATE/AIR-RETURN/CENTRAL": (92000, "17:55"),
}
for key, (total, ready) in expected.items():
    row = by_id[key]
    assert (row["total"], row["ready"].strftime("%H:%M")) == (total, ready), key
assert len(rows) == 18
assert sum(not row["reasons"] for row in rows) == 12
assert min(row["total"] for row in rows if not row["reasons"]) == 84000
assert all("late hotel arrival" in row["reasons"] for row in rows if row["id"].startswith("AIR-LATE/"))
assert by_id["RAIL-OUT/RAIL-RETURN/GARDEN"]["home"].strftime("%H:%M") == "22:15"

lines = ["# Calculated fixture combinations", "", "Generated by `python scripts/verify-design.py`; fictional design inventory only.", "",
         "All totals cover two travelers, one room for two nights, and transfers in both cities.", "",
         "| Outbound / return / hotel | Transport | Hotel | Transfers | Total | Hotel ready Fri | Leave hotel Sun | Boston return Sun | Result |",
         "| --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- |"]
for row in rows:
    money = [f'${row[key] / 100:,.2f}' for key in ("transport", "lodging", "transfers", "total")]
    times = [row[key].strftime("%H:%M") for key in ("ready", "leave", "home")]
    lines.append("| " + " | ".join([row["id"], *money, *times, ", ".join(row["reasons"]) or "Feasible"]) + " |")
(ROOT / "docs/calculated-combinations.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("Verified 18 combinations: 12 feasible, 6 late; minimum feasible total $840.")
print("Updated docs/calculated-combinations.md")
