CREATE TABLE detour_trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    owner_user_id BIGINT NOT NULL,
    catalog_destination_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    traveler_count SMALLINT NOT NULL,
    budget_cents BIGINT,
    display_label VARCHAR(300) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_detour_trip_public_id UNIQUE (public_id),
    CONSTRAINT fk_detour_trip_owner FOREIGN KEY (owner_user_id) REFERENCES detour_user(id),
    CONSTRAINT fk_detour_trip_destination FOREIGN KEY (catalog_destination_id) REFERENCES catalog_destination(id),
    CONSTRAINT ck_detour_trip_dates CHECK (start_date >= DATE '2027-03-01' AND end_date <= DATE '2027-03-31' AND DATEDIFF('DAY', start_date, end_date) BETWEEN 1 AND 14),
    CONSTRAINT ck_detour_trip_travelers CHECK (traveler_count BETWEEN 1 AND 8),
    CONSTRAINT ck_detour_trip_budget CHECK (budget_cents IS NULL OR budget_cents BETWEEN 0 AND 100000000),
    CONSTRAINT ck_detour_trip_version CHECK (version >= 0)
);

CREATE INDEX ix_detour_trip_owner_public_id ON detour_trip (owner_user_id, public_id);

CREATE TABLE detour_trip_traveler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    traveler_ordinal SMALLINT NOT NULL,
    age SMALLINT,
    CONSTRAINT uq_detour_trip_traveler_ordinal UNIQUE (trip_id, traveler_ordinal),
    CONSTRAINT fk_detour_trip_traveler_trip FOREIGN KEY (trip_id) REFERENCES detour_trip(id),
    CONSTRAINT ck_detour_trip_traveler_ordinal CHECK (traveler_ordinal BETWEEN 1 AND 8),
    CONSTRAINT ck_detour_trip_traveler_age CHECK (age IS NULL OR age BETWEEN 0 AND 120)
);

CREATE INDEX ix_detour_trip_traveler_trip_id ON detour_trip_traveler (trip_id);

CREATE TABLE detour_trip_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    trip_id BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_detour_trip_draft_public_id UNIQUE (public_id),
    CONSTRAINT uq_detour_trip_draft_trip_id UNIQUE (trip_id),
    CONSTRAINT fk_detour_trip_draft_trip FOREIGN KEY (trip_id) REFERENCES detour_trip(id),
    CONSTRAINT ck_detour_trip_draft_version CHECK (version >= 0)
);

CREATE INDEX ix_detour_trip_draft_trip_id ON detour_trip_draft (trip_id);
