-- A Draft holds only mutable catalog references.  Planned rows below deliberately
-- copy the resolved facts used for display; they are never reconstructed from a
-- live catalog join.
CREATE TABLE detour_trip_draft_airfare_selection (
    draft_id BIGINT PRIMARY KEY,
    outbound_flight_instance_id BIGINT NOT NULL,
    return_flight_instance_id BIGINT NOT NULL,
    CONSTRAINT fk_draft_airfare_draft FOREIGN KEY (draft_id) REFERENCES detour_trip_draft(id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_airfare_outbound FOREIGN KEY (outbound_flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT fk_draft_airfare_return FOREIGN KEY (return_flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT ck_draft_airfare_distinct CHECK (outbound_flight_instance_id <> return_flight_instance_id)
);

CREATE TABLE detour_trip_draft_stay_selection (
    draft_id BIGINT PRIMARY KEY,
    accommodation_unit_id BIGINT NOT NULL,
    unit_count INTEGER NOT NULL,
    CONSTRAINT fk_draft_stay_draft FOREIGN KEY (draft_id) REFERENCES detour_trip_draft(id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_stay_unit FOREIGN KEY (accommodation_unit_id) REFERENCES accommodation_unit(id),
    CONSTRAINT ck_draft_stay_units CHECK (unit_count > 0)
);

CREATE TABLE detour_trip_draft_rental_selection (
    draft_id BIGINT PRIMARY KEY,
    rental_unit_id BIGINT NOT NULL,
    pickup_at TIMESTAMP WITH TIME ZONE NOT NULL,
    return_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_draft_rental_draft FOREIGN KEY (draft_id) REFERENCES detour_trip_draft(id) ON DELETE CASCADE,
    CONSTRAINT fk_draft_rental_unit FOREIGN KEY (rental_unit_id) REFERENCES rental_unit(id),
    CONSTRAINT ck_draft_rental_times CHECK (pickup_at < return_at)
);

CREATE TABLE detour_planned_itinerary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    trip_id BIGINT NOT NULL,
    CONSTRAINT uq_planned_itinerary_public_id UNIQUE (public_id),
    CONSTRAINT fk_planned_itinerary_trip FOREIGN KEY (trip_id) REFERENCES detour_trip(id) ON DELETE CASCADE
);
CREATE INDEX idx_planned_itinerary_trip ON detour_planned_itinerary (trip_id, id);

CREATE TABLE detour_planned_airfare_snapshot (
    planned_itinerary_id BIGINT PRIMARY KEY,
    outbound_flight_instance_id BIGINT NOT NULL,
    return_flight_instance_id BIGINT NOT NULL,
    outbound_description VARCHAR(300) NOT NULL,
    return_description VARCHAR(300) NOT NULL,
    outbound_base_fare_cents BIGINT NOT NULL,
    outbound_tax_cents BIGINT NOT NULL,
    outbound_fee_cents BIGINT NOT NULL,
    return_base_fare_cents BIGINT NOT NULL,
    return_tax_cents BIGINT NOT NULL,
    return_fee_cents BIGINT NOT NULL,
    CONSTRAINT fk_planned_airfare_itinerary FOREIGN KEY (planned_itinerary_id) REFERENCES detour_planned_itinerary(id) ON DELETE CASCADE,
    CONSTRAINT fk_planned_airfare_outbound FOREIGN KEY (outbound_flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT fk_planned_airfare_return FOREIGN KEY (return_flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT ck_planned_airfare_money CHECK (outbound_base_fare_cents >= 0 AND outbound_tax_cents >= 0 AND outbound_fee_cents >= 0 AND return_base_fare_cents >= 0 AND return_tax_cents >= 0 AND return_fee_cents >= 0)
);

CREATE TABLE detour_planned_stay_snapshot (
    planned_itinerary_id BIGINT PRIMARY KEY,
    accommodation_unit_id BIGINT NOT NULL,
    unit_count INTEGER NOT NULL,
    property_name VARCHAR(200) NOT NULL,
    unit_name VARCHAR(200) NOT NULL,
    CONSTRAINT fk_planned_stay_itinerary FOREIGN KEY (planned_itinerary_id) REFERENCES detour_planned_itinerary(id) ON DELETE CASCADE,
    CONSTRAINT fk_planned_stay_unit FOREIGN KEY (accommodation_unit_id) REFERENCES accommodation_unit(id),
    CONSTRAINT ck_planned_stay_units CHECK (unit_count > 0)
);
CREATE TABLE detour_planned_stay_night_snapshot (
    planned_itinerary_id BIGINT NOT NULL,
    night_date DATE NOT NULL,
    base_price_cents BIGINT NOT NULL,
    tax_cents BIGINT NOT NULL,
    fee_cents BIGINT NOT NULL,
    PRIMARY KEY (planned_itinerary_id, night_date),
    CONSTRAINT fk_planned_stay_night FOREIGN KEY (planned_itinerary_id) REFERENCES detour_planned_stay_snapshot(planned_itinerary_id) ON DELETE CASCADE,
    CONSTRAINT ck_planned_stay_night_money CHECK (base_price_cents >= 0 AND tax_cents >= 0 AND fee_cents >= 0)
);

CREATE TABLE detour_planned_rental_snapshot (
    planned_itinerary_id BIGINT PRIMARY KEY,
    rental_unit_id BIGINT NOT NULL,
    pickup_at TIMESTAMP WITH TIME ZONE NOT NULL,
    return_at TIMESTAMP WITH TIME ZONE NOT NULL,
    location_name VARCHAR(200) NOT NULL,
    vehicle_class_name VARCHAR(200) NOT NULL,
    unit_identifier VARCHAR(100) NOT NULL,
    daily_base_price_cents BIGINT NOT NULL,
    daily_tax_cents BIGINT NOT NULL,
    daily_fee_cents BIGINT NOT NULL,
    CONSTRAINT fk_planned_rental_itinerary FOREIGN KEY (planned_itinerary_id) REFERENCES detour_planned_itinerary(id) ON DELETE CASCADE,
    CONSTRAINT fk_planned_rental_unit FOREIGN KEY (rental_unit_id) REFERENCES rental_unit(id),
    CONSTRAINT ck_planned_rental_times CHECK (pickup_at < return_at),
    CONSTRAINT ck_planned_rental_money CHECK (daily_base_price_cents >= 0 AND daily_tax_cents >= 0 AND daily_fee_cents >= 0)
);
