-- V17__create_booking_schema.sql
-- Create detour_booking table and frozen component snapshot tables.

CREATE TABLE detour_booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    trip_id BIGINT NOT NULL,
    planned_itinerary_id BIGINT NOT NULL,
    booking_reference VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    grand_total_cents BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    canceled_at TIMESTAMP WITH TIME ZONE,
    airfare_reference VARCHAR(20),
    stay_reference VARCHAR(20),
    rental_reference VARCHAR(20),
    rental_occupancy_id BIGINT,
    active_trip_id BIGINT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN trip_id ELSE NULL END),
    CONSTRAINT uq_detour_booking_public_id UNIQUE (public_id),
    CONSTRAINT uq_detour_booking_reference UNIQUE (booking_reference),
    CONSTRAINT fk_booking_trip FOREIGN KEY (trip_id) REFERENCES detour_trip(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_planned_itinerary FOREIGN KEY (planned_itinerary_id) REFERENCES detour_planned_itinerary(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_rental_occupancy FOREIGN KEY (rental_occupancy_id) REFERENCES rental_unit_occupancy(id),
    CONSTRAINT ck_detour_booking_status CHECK (status IN ('ACTIVE', 'CANCELED')),
    CONSTRAINT ck_detour_booking_grand_total CHECK (grand_total_cents >= 0),
    CONSTRAINT uq_detour_booking_active_trip UNIQUE (active_trip_id),
    CONSTRAINT uq_detour_booking_trip_idempotency UNIQUE (trip_id, idempotency_key)
);

CREATE INDEX idx_detour_booking_trip ON detour_booking (trip_id, created_at DESC);

CREATE TABLE detour_booking_airfare_snapshot (
    booking_id BIGINT PRIMARY KEY,
    outbound_flight_instance_id BIGINT NOT NULL,
    return_flight_instance_id BIGINT NOT NULL,
    outbound_description VARCHAR(300) NOT NULL,
    return_description VARCHAR(300) NOT NULL,
    outbound_base_fare_cents BIGINT NOT NULL,
    outbound_tax_cents BIGINT NOT NULL,
    outbound_fee_cents BIGINT NOT NULL,
    return_base_fare_cents BIGINT NOT NULL,
    return_tax_cents BIGINT NOT NULL,
    return_fee_cents BIGINT NOT NULL,
    outbound_carrier_name VARCHAR(200),
    outbound_flight_number VARCHAR(50),
    outbound_stop_count INTEGER,
    outbound_layover_airport_code VARCHAR(10),
    outbound_layover_duration_minutes INTEGER,
    outbound_departure_time TIMESTAMP WITH TIME ZONE,
    outbound_arrival_time TIMESTAMP WITH TIME ZONE,
    outbound_departure_timezone VARCHAR(100),
    outbound_arrival_timezone VARCHAR(100),
    outbound_duration_minutes INTEGER,
    return_carrier_name VARCHAR(200),
    return_flight_number VARCHAR(50),
    return_stop_count INTEGER,
    return_layover_airport_code VARCHAR(10),
    return_layover_duration_minutes INTEGER,
    return_departure_time TIMESTAMP WITH TIME ZONE,
    return_arrival_time TIMESTAMP WITH TIME ZONE,
    return_departure_timezone VARCHAR(100),
    return_arrival_timezone VARCHAR(100),
    return_duration_minutes INTEGER,
    total_duration_minutes INTEGER,
    CONSTRAINT fk_booking_airfare_booking FOREIGN KEY (booking_id) REFERENCES detour_booking(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_airfare_outbound FOREIGN KEY (outbound_flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT fk_booking_airfare_return FOREIGN KEY (return_flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT ck_booking_airfare_money CHECK (
        outbound_base_fare_cents >= 0 AND outbound_tax_cents >= 0 AND outbound_fee_cents >= 0 AND
        return_base_fare_cents >= 0 AND return_tax_cents >= 0 AND return_fee_cents >= 0
    )
);

CREATE TABLE detour_booking_stay_snapshot (
    booking_id BIGINT PRIMARY KEY,
    accommodation_unit_id BIGINT NOT NULL,
    unit_count INTEGER NOT NULL,
    property_name VARCHAR(200) NOT NULL,
    unit_name VARCHAR(200) NOT NULL,
    property_category VARCHAR(50),
    location_description VARCHAR(500),
    distance_to_city_center_meters INTEGER,
    guest_capacity INTEGER,
    required_room_count INTEGER,
    CONSTRAINT fk_booking_stay_booking FOREIGN KEY (booking_id) REFERENCES detour_booking(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_stay_unit FOREIGN KEY (accommodation_unit_id) REFERENCES accommodation_unit(id),
    CONSTRAINT ck_booking_stay_units CHECK (unit_count > 0)
);

CREATE TABLE detour_booking_stay_night_snapshot (
    booking_id BIGINT NOT NULL,
    night_date DATE NOT NULL,
    base_price_cents BIGINT NOT NULL,
    tax_cents BIGINT NOT NULL,
    fee_cents BIGINT NOT NULL,
    PRIMARY KEY (booking_id, night_date),
    CONSTRAINT fk_booking_stay_night FOREIGN KEY (booking_id) REFERENCES detour_booking_stay_snapshot(booking_id) ON DELETE CASCADE,
    CONSTRAINT ck_booking_stay_night_money CHECK (base_price_cents >= 0 AND tax_cents >= 0 AND fee_cents >= 0)
);

CREATE TABLE detour_booking_rental_snapshot (
    booking_id BIGINT PRIMARY KEY,
    rental_unit_id BIGINT NOT NULL,
    pickup_at TIMESTAMP WITH TIME ZONE NOT NULL,
    return_at TIMESTAMP WITH TIME ZONE NOT NULL,
    location_name VARCHAR(200) NOT NULL,
    vehicle_class_name VARCHAR(200) NOT NULL,
    unit_identifier VARCHAR(100) NOT NULL,
    daily_base_price_cents BIGINT NOT NULL,
    daily_tax_cents BIGINT NOT NULL,
    daily_fee_cents BIGINT NOT NULL,
    vehicle_category VARCHAR(50),
    CONSTRAINT fk_booking_rental_booking FOREIGN KEY (booking_id) REFERENCES detour_booking(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_rental_unit FOREIGN KEY (rental_unit_id) REFERENCES rental_unit(id),
    CONSTRAINT ck_booking_rental_times CHECK (pickup_at < return_at),
    CONSTRAINT ck_booking_rental_money CHECK (daily_base_price_cents >= 0 AND daily_tax_cents >= 0 AND daily_fee_cents >= 0)
);

CREATE VIEW detour_booking_item_snapshot AS
SELECT booking_id, 'AIRFARE' AS item_type,
       outbound_description || ' / ' || return_description AS item_description,
       (outbound_base_fare_cents + outbound_tax_cents + outbound_fee_cents + return_base_fare_cents + return_tax_cents + return_fee_cents) AS total_cents
FROM detour_booking_airfare_snapshot
UNION ALL
SELECT s.booking_id, 'STAY' AS item_type,
       s.property_name || ' - ' || s.unit_name AS item_description,
       COALESCE(SUM(n.base_price_cents + n.tax_cents + n.fee_cents), 0) * s.unit_count AS total_cents
FROM detour_booking_stay_snapshot s
LEFT JOIN detour_booking_stay_night_snapshot n ON n.booking_id = s.booking_id
GROUP BY s.booking_id, s.property_name, s.unit_name, s.unit_count
UNION ALL
SELECT booking_id, 'RENTAL' AS item_type,
       vehicle_class_name || ' (' || location_name || ')' AS item_description,
       (daily_base_price_cents + daily_tax_cents + daily_fee_cents) AS total_cents
FROM detour_booking_rental_snapshot;
