CREATE TABLE catalog_destination (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    latitude DECIMAL(8, 5) NOT NULL,
    longitude DECIMAL(8, 5) NOT NULL,
    CONSTRAINT uq_catalog_destination_key UNIQUE (catalog_key),
    CONSTRAINT ck_catalog_destination_country CHECK (CHAR_LENGTH(country_code) = 2),
    CONSTRAINT ck_catalog_destination_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_catalog_destination_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE catalog_airport (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    iata_code VARCHAR(3) NOT NULL,
    name VARCHAR(200) NOT NULL,
    destination_id BIGINT,
    latitude DECIMAL(8, 5) NOT NULL,
    longitude DECIMAL(8, 5) NOT NULL,
    time_zone_id VARCHAR(100) NOT NULL,
    CONSTRAINT uq_catalog_airport_key UNIQUE (catalog_key),
    CONSTRAINT uq_catalog_airport_iata UNIQUE (iata_code),
    CONSTRAINT uq_catalog_airport_destination UNIQUE (id, destination_id),
    CONSTRAINT fk_catalog_airport_destination FOREIGN KEY (destination_id) REFERENCES catalog_destination(id),
    CONSTRAINT ck_catalog_airport_iata CHECK (CHAR_LENGTH(iata_code) = 3),
    CONSTRAINT ck_catalog_airport_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_catalog_airport_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_catalog_airport_time_zone CHECK (CHAR_LENGTH(time_zone_id) > 0)
);

CREATE TABLE catalog_supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    supplier_category VARCHAR(20) NOT NULL,
    CONSTRAINT uq_catalog_supplier_key UNIQUE (catalog_key),
    CONSTRAINT uq_catalog_supplier_category UNIQUE (id, supplier_category),
    CONSTRAINT ck_catalog_supplier_category CHECK (supplier_category IN ('AIRLINE', 'LODGING', 'CAR_RENTAL'))
);

CREATE TABLE flight_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    supplier_id BIGINT NOT NULL,
    supplier_category VARCHAR(20) NOT NULL,
    flight_number VARCHAR(20) NOT NULL,
    origin_airport_id BIGINT NOT NULL,
    destination_airport_id BIGINT NOT NULL,
    stop_count SMALLINT NOT NULL,
    segment_count SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT uq_flight_schedule_key UNIQUE (catalog_key),
    CONSTRAINT uq_flight_schedule_segment_count UNIQUE (id, segment_count),
    CONSTRAINT uq_flight_schedule_number UNIQUE (supplier_id, flight_number),
    CONSTRAINT fk_flight_schedule_supplier FOREIGN KEY (supplier_id, supplier_category) REFERENCES catalog_supplier(id, supplier_category),
    CONSTRAINT fk_flight_schedule_origin FOREIGN KEY (origin_airport_id) REFERENCES catalog_airport(id),
    CONSTRAINT fk_flight_schedule_destination FOREIGN KEY (destination_airport_id) REFERENCES catalog_airport(id),
    CONSTRAINT ck_flight_schedule_route CHECK (origin_airport_id <> destination_airport_id),
    CONSTRAINT ck_flight_schedule_supplier CHECK (supplier_category = 'AIRLINE'),
    CONSTRAINT ck_flight_schedule_stop_count CHECK (stop_count IN (0, 1)),
    CONSTRAINT ck_flight_schedule_segment_count CHECK (segment_count = stop_count + 1)
);

CREATE TABLE flight_schedule_segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_schedule_id BIGINT NOT NULL,
    segment_ordinal SMALLINT NOT NULL,
    origin_airport_id BIGINT NOT NULL,
    destination_airport_id BIGINT NOT NULL,
    departure_local_time TIME NOT NULL,
    arrival_local_time TIME NOT NULL,
    arrival_day_offset SMALLINT NOT NULL,
    scheduled_duration_minutes INTEGER NOT NULL,
    CONSTRAINT uq_flight_schedule_segment_ordinal UNIQUE (flight_schedule_id, segment_ordinal),
    CONSTRAINT fk_flight_schedule_segment_schedule FOREIGN KEY (flight_schedule_id) REFERENCES flight_schedule(id),
    CONSTRAINT fk_flight_schedule_segment_origin FOREIGN KEY (origin_airport_id) REFERENCES catalog_airport(id),
    CONSTRAINT fk_flight_schedule_segment_destination FOREIGN KEY (destination_airport_id) REFERENCES catalog_airport(id),
    CONSTRAINT ck_flight_schedule_segment_ordinal CHECK (segment_ordinal IN (1, 2)),
    CONSTRAINT ck_flight_schedule_segment_route CHECK (origin_airport_id <> destination_airport_id),
    CONSTRAINT ck_flight_schedule_segment_arrival_day CHECK (arrival_day_offset IN (0, 1, 2)),
    CONSTRAINT ck_flight_schedule_segment_duration CHECK (scheduled_duration_minutes > 0)
);

CREATE TABLE flight_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    flight_schedule_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    segment_count SMALLINT NOT NULL DEFAULT 1,
    base_fare_cents BIGINT NOT NULL,
    tax_cents BIGINT NOT NULL,
    fee_cents BIGINT NOT NULL,
    seat_capacity INTEGER NOT NULL,
    available_seats INTEGER NOT NULL,
    CONSTRAINT uq_flight_instance_key UNIQUE (catalog_key),
    CONSTRAINT uq_flight_instance_schedule_date UNIQUE (flight_schedule_id, service_date),
    CONSTRAINT fk_flight_instance_schedule FOREIGN KEY (flight_schedule_id, segment_count) REFERENCES flight_schedule(id, segment_count),
    CONSTRAINT ck_flight_instance_segment_count CHECK (segment_count IN (1, 2)),
    CONSTRAINT ck_flight_instance_base_fare CHECK (base_fare_cents >= 0),
    CONSTRAINT ck_flight_instance_tax CHECK (tax_cents >= 0),
    CONSTRAINT ck_flight_instance_fee CHECK (fee_cents >= 0),
    CONSTRAINT ck_flight_instance_seat_capacity CHECK (seat_capacity > 0),
    CONSTRAINT ck_flight_instance_available_seats CHECK (available_seats BETWEEN 0 AND seat_capacity)
);

CREATE TABLE flight_instance_segment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_instance_id BIGINT NOT NULL,
    segment_ordinal SMALLINT NOT NULL,
    departure_at TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_flight_instance_segment_ordinal UNIQUE (flight_instance_id, segment_ordinal),
    CONSTRAINT fk_flight_instance_segment_instance FOREIGN KEY (flight_instance_id) REFERENCES flight_instance(id),
    CONSTRAINT ck_flight_instance_segment_ordinal CHECK (segment_ordinal IN (1, 2)),
    CONSTRAINT ck_flight_instance_segment_times CHECK (departure_at < arrival_at)
);
