CREATE TABLE accommodation_property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    supplier_id BIGINT NOT NULL,
    supplier_category VARCHAR(20) NOT NULL,
    destination_id BIGINT NOT NULL,
    property_category VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    CONSTRAINT uq_accommodation_property_key UNIQUE (catalog_key),
    CONSTRAINT uq_accommodation_property_category UNIQUE (id, property_category),
    CONSTRAINT fk_accommodation_property_supplier FOREIGN KEY (supplier_id, supplier_category) REFERENCES catalog_supplier(id, supplier_category),
    CONSTRAINT fk_accommodation_property_destination FOREIGN KEY (destination_id) REFERENCES catalog_destination(id),
    CONSTRAINT ck_accommodation_property_category CHECK (property_category IN ('HOTEL', 'BED_AND_BREAKFAST', 'VACATION_RENTAL')),
    CONSTRAINT ck_accommodation_property_supplier CHECK (supplier_category = 'LODGING')
);

CREATE TABLE accommodation_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    accommodation_property_id BIGINT NOT NULL,
    property_category VARCHAR(30) NOT NULL,
    unit_kind VARCHAR(20) NOT NULL,
    guest_capacity INTEGER NOT NULL,
    inventory_capacity INTEGER NOT NULL,
    name VARCHAR(200) NOT NULL,
    CONSTRAINT uq_accommodation_unit_key UNIQUE (catalog_key),
    CONSTRAINT uq_accommodation_unit_capacity UNIQUE (id, inventory_capacity),
    CONSTRAINT fk_accommodation_unit_property FOREIGN KEY (accommodation_property_id, property_category) REFERENCES accommodation_property(id, property_category),
    CONSTRAINT ck_accommodation_unit_kind CHECK (unit_kind IN ('ROOM', 'WHOLE_PROPERTY')),
    CONSTRAINT ck_accommodation_unit_pairing CHECK (
        (property_category IN ('HOTEL', 'BED_AND_BREAKFAST') AND unit_kind = 'ROOM')
        OR (property_category = 'VACATION_RENTAL' AND unit_kind = 'WHOLE_PROPERTY')
    ),
    CONSTRAINT ck_accommodation_unit_guest_capacity CHECK (guest_capacity > 0),
    CONSTRAINT ck_accommodation_unit_inventory_capacity CHECK (inventory_capacity > 0)
);

CREATE TABLE accommodation_nightly_inventory (
    accommodation_unit_id BIGINT NOT NULL,
    night_date DATE NOT NULL,
    inventory_capacity INTEGER NOT NULL,
    available_inventory INTEGER NOT NULL,
    base_price_cents BIGINT NOT NULL,
    tax_cents BIGINT NOT NULL,
    fee_cents BIGINT NOT NULL,
    PRIMARY KEY (accommodation_unit_id, night_date),
    CONSTRAINT fk_accommodation_nightly_unit_capacity FOREIGN KEY (accommodation_unit_id, inventory_capacity) REFERENCES accommodation_unit(id, inventory_capacity),
    CONSTRAINT ck_accommodation_nightly_available CHECK (available_inventory BETWEEN 0 AND inventory_capacity),
    CONSTRAINT ck_accommodation_nightly_base_price CHECK (base_price_cents >= 0),
    CONSTRAINT ck_accommodation_nightly_tax CHECK (tax_cents >= 0),
    CONSTRAINT ck_accommodation_nightly_fee CHECK (fee_cents >= 0)
);

CREATE TABLE rental_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    destination_id BIGINT NOT NULL,
    airport_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    CONSTRAINT uq_rental_location_key UNIQUE (catalog_key),
    CONSTRAINT uq_rental_location_airport UNIQUE (airport_id),
    CONSTRAINT fk_rental_location_destination FOREIGN KEY (destination_id) REFERENCES catalog_destination(id),
    CONSTRAINT fk_rental_location_destination_airport FOREIGN KEY (airport_id, destination_id) REFERENCES catalog_airport(id, destination_id)
);

CREATE TABLE rental_vehicle_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    supplier_id BIGINT NOT NULL,
    supplier_category VARCHAR(20) NOT NULL,
    rental_location_id BIGINT NOT NULL,
    vehicle_category VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    daily_base_price_cents BIGINT NOT NULL,
    daily_tax_cents BIGINT NOT NULL,
    daily_fee_cents BIGINT NOT NULL,
    CONSTRAINT uq_rental_vehicle_class_key UNIQUE (catalog_key),
    CONSTRAINT fk_rental_vehicle_class_supplier FOREIGN KEY (supplier_id, supplier_category) REFERENCES catalog_supplier(id, supplier_category),
    CONSTRAINT fk_rental_vehicle_class_location FOREIGN KEY (rental_location_id) REFERENCES rental_location(id),
    CONSTRAINT ck_rental_vehicle_class_supplier CHECK (supplier_category = 'CAR_RENTAL'),
    CONSTRAINT ck_rental_vehicle_class_category CHECK (vehicle_category IN ('ECONOMY', 'STANDARD', 'SUV')),
    CONSTRAINT ck_rental_vehicle_class_base_price CHECK (daily_base_price_cents >= 0),
    CONSTRAINT ck_rental_vehicle_class_tax CHECK (daily_tax_cents >= 0),
    CONSTRAINT ck_rental_vehicle_class_fee CHECK (daily_fee_cents >= 0)
);

CREATE TABLE rental_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_key VARCHAR(100) NOT NULL,
    rental_vehicle_class_id BIGINT NOT NULL,
    unit_identifier VARCHAR(100) NOT NULL,
    CONSTRAINT uq_rental_unit_key UNIQUE (catalog_key),
    CONSTRAINT uq_rental_unit_identifier UNIQUE (rental_vehicle_class_id, unit_identifier),
    CONSTRAINT fk_rental_unit_vehicle_class FOREIGN KEY (rental_vehicle_class_id) REFERENCES rental_vehicle_class(id)
);

CREATE TABLE rental_unit_occupancy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_unit_id BIGINT NOT NULL,
    pickup_at TIMESTAMP WITH TIME ZONE NOT NULL,
    return_at TIMESTAMP WITH TIME ZONE NOT NULL,
    occupancy_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rental_unit_occupancy_unit FOREIGN KEY (rental_unit_id) REFERENCES rental_unit(id),
    CONSTRAINT ck_rental_unit_occupancy_times CHECK (pickup_at < return_at),
    CONSTRAINT ck_rental_unit_occupancy_status CHECK (occupancy_status IN ('ACTIVE', 'RELEASED'))
);

CREATE INDEX idx_rental_unit_occupancy_overlap ON rental_unit_occupancy (rental_unit_id, occupancy_status, pickup_at, return_at);

CREATE TRIGGER rental_unit_occupancy_overlap
BEFORE INSERT, UPDATE ON rental_unit_occupancy
FOR EACH ROW CALL "app.detour.catalog.persistence.RentalUnitOccupancyOverlapTrigger";
